name: Run Rustfmt

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
            toolchain: nightly
            components: rustfmt
            override: true

      - name: Reformat
        run: cargo +nightly fmt

      - name: Package
        run: nox -s bot-package-diff

      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: gogo.patch
          path: gogo.patch

      - name: Check diff file
        run: nox -s is-diff-file-empty
